name: Analisis de calidad

on: pull_request

jobs:
  calidad:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
    - name: Bajar codigo
      uses: actions/checkout@v4

    - name: Instalar librerias
      run: |
        python -m pip install --upgrade pip
        pip install pytest 

    - name: Ejecutar codigo
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: pylint
        
    - name: Ejecutar test
      run: pytest test.py
