name: Workflow 2

on: pull_request

jobs: 
  tareas:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: bajar codigo
        uses: actions/checkout@v4

      - name: mirar code
        uses: advanced-security/python-lint-code-scanning-action@v1

