name: Test Workflow

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Bajar codigo
      uses: actions/checkout@v4

    - name: Instalar librerias
      run: |
        python -m pip install --upgrade pip
        pip install pytest 
        
    - name: Ejecutar test
      run: pytest test.py
