name: workflow linter

on: pull_request

jobs:
  tareas:
  
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: analizar calidad codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
