name: workflow

on: pull_request

jobs:
  sumatest:
  
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps: 
      - name: Descargar codigo
        uses: actions/checkout@v4
        
      - name: analizar calidad codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
