name: Mi workflow

on: pull_request

jobs: 
  tareas: 
    runs-on: ubuntu-latest
    permissions: 
      security-events: write
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4

      - name: Probar codigo
        run: python3 main.py

      - name: Medir Calidad del codigo
        uses:  advanced-security/python-lint-code-scanning-action@v1
